services:
  # nginx [web-server]
  web:
    image: nginx:latest
    container_name: taskify_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certs:/etc/nginx/ssl

  # php [language - interpreter]
  app:
    container_name: taskify_app
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html

  # mysql [database]
  db:
    image: mysql:8.4
    container_name: taskify_database
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskify
      MYSQL_USER: taskify
      MYSQL_PASSWORD: taskify

volumes:
  mysqldata: