services:
  # nginx [web-server]
  web:
    image: nginx:latest
    container_name: taskify_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certs:/etc/nginx/ssl

  # php [language - interpreter]
  app:
    container_name: taskify_app
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html

  # mysql [database]
  db:
    image: postgres:16.6
    container_name: taskify_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskify
      POSTGRES_USER: taskify
      POSTGRES_PASSWORD: taskify

volumes:
  pgdata: